name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        dir: [basic, basic-ts, create-react-app, playwright-video, create-react-app-coverage, nextjs-coverage]
        platform: [ubuntu-latest, windows-latest]
        node: ['12', '14']
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
      working-directory: ${{ matrix.dir }}
    - run: npm test
      working-directory: ${{ matrix.dir }}
      env:
        SKIP_PREFLIGHT_CHECK: "true"
    - name: Coveralls
      uses: coverallsapp/github-action@master
      if: ${{ matrix.dir == 'create-react-app-coverage' }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: create-react-app-coverage/coverage/lcov.info
        base-path: ${{ matrix.dir }}
