name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [basic, basic-ts, create-react-app, playwright-video, create-react-app-coverage]
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
      working-directory: ${{ matrix.dir }}
    - run: npm test
      working-directory: ${{ matrix.dir }}
      env:
        SKIP_PREFLIGHT_CHECK: "true"
    - name: Coveralls
      if: ${{ matrix.dir == 'create-react-app-coverage' }}
      run: npx coveralls -v < coverage/lcov.info
      working-directory: ${{ matrix.dir }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
